apiVersion: v1
data:
  REDIS_OUTPUT_KEY: 2020006973-proj3-output
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-10T11:31:07Z"
  name: outputkey
  namespace: raphaelasilva
  resourceVersion: "31538303"
  uid: 175ccfd7-17a8-423c-adeb-3ee1a4ac38e5